networks:
  caddy_network:
    external: true
  postgres_network:
    external: true

services:
  sura_fe:
    image: ghcr.io/asman1337/sura-frontend:latest
    container_name: sura_frontend
    restart: unless-stopped
    environment:
       - VITE_API_URL=https://api.sura.otmalse.in
    networks:
      - caddy_network

  sura_be:
    image: ghcr.io/asman1337/sura-backend:latest
    container_name: sura_backend
    restart: unless-stopped
    networks:
      - caddy_network
      - postgres_network
    environment:
      # Environment
      - NODE_ENV=production
      - PORT=3000
      # CORS Configuration
      - CORS_ORIGIN=https://sura.otmalse.in,http://localhost:5173,http://localhost:3000
      # Database (matching app.module.ts expectations)
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=medmart_d4rky
      - DATABASE_PASSWORD=Mr.D4rky007@medmart
      - DATABASE_NAME=medmart_database
      - DATABASE_LOGGING=false
      # Authentication
      - JWT_SECRET=5ygs89sfw9uf9nsf89dsfny7y4er5fg
      - JWT_EXPIRES_IN=3d
      - JWT_REFRESH_SECRET=87cadf7b98fa7a8duig6zc76cb3f4d8c9
      - JWT_REFRESH_EXPIRES_IN=7d
    volumes:
      - medmart_data:/app/logs

volumes:
  medmart_data:
    driver: local